# Generated by Django 4.0.1 on 2022-01-13 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10000)),
                ('describe', models.TextField()),
                ('attachments', models.FileField(upload_to='')),
            ],
        ),
    ]
