# Generated by Django 4.0.1 on 2022-01-14 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mails',
            name='attachments',
            field=models.FileField(upload_to='files/'),
        ),
    ]
