# Generated by Django 4.0.1 on 2022-01-17 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0004_users_attempts_users_email_id_users_employee_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='employee_id',
            field=models.CharField(default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='status',
            field=models.CharField(max_length=20),
        ),
    ]
