# Generated by Django 4.0.1 on 2022-01-17 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0005_alter_users_employee_id_alter_users_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='status',
            field=models.BooleanField(),
        ),
    ]
