# Generated by Django 4.0.1 on 2022-01-17 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0006_alter_users_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
