# Generated by Django 4.0.1 on 2022-01-22 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0008_mail_members_alter_users_attempts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail_members',
            name='industry_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mail_members',
            name='phone_number',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
