# Generated by Django 4.0.1 on 2022-01-23 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0009_mail_members_industry_name_mail_members_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='mail_members',
            name='email_address',
            field=models.EmailField(default='demo@gmail.com', max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='group_members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=100)),
                ('email_address', models.EmailField(max_length=100, null=True)),
                ('group_members', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mails.mail_members')),
            ],
        ),
    ]
