# Generated by Django 4.0.1 on 2022-01-23 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0010_groups_alter_mail_members_email_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group_members',
            name='group_members',
        ),
    ]
