# Generated by Django 4.0.1 on 2022-01-24 18:48

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0011_remove_group_members_group_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mails',
            name='describe',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
