# Generated by Django 4.0.1 on 2022-01-25 05:58

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0012_alter_mails_describe'),
    ]

    operations = [
        migrations.CreateModel(
            name='sent_mails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('by', models.EmailField(max_length=1000)),
                ('to', models.CharField(max_length=1000)),
                ('bcc', models.CharField(blank=True, max_length=1000, null=True)),
                ('cc', models.CharField(blank=True, max_length=1000, null=True)),
                ('subject', models.CharField(max_length=1000)),
                ('describe', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('attachments', models.FileField(upload_to='files/')),
            ],
        ),
    ]
