# Generated by Django 3.2.11 on 2022-02-03 12:07

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0014_sent_mails_date_sent_mails_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='schedulemails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('by', models.EmailField(max_length=1000)),
                ('to', models.CharField(max_length=10000)),
                ('bcc', models.CharField(blank=True, max_length=1000, null=True)),
                ('cc', models.CharField(blank=True, max_length=1000, null=True)),
                ('subject', models.CharField(max_length=1000)),
                ('describe', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('attachments', models.FileField(upload_to='files/')),
                ('date', models.CharField(blank=True, max_length=25, null=True)),
                ('time', models.CharField(blank=True, max_length=25, null=True)),
            ],
        ),
    ]
