# Generated by Django 3.2.11 on 2022-02-04 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0015_schedulemails'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulemails',
            name='session_user',
            field=models.EmailField(blank=True, max_length=1000, null=True),
        ),
    ]
