# Generated by Django 3.2.11 on 2022-02-09 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0017_dailymails'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='dailymails',
            new_name='dailymailsdatabase',
        ),
    ]
