# Generated by Django 3.2.11 on 2022-02-11 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0020_monthlymailsdatabase'),
    ]

    operations = [
        migrations.AddField(
            model_name='mails',
            name='extension',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='dailymailsdatabase',
            name='status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
