# Generated by Django 3.2.11 on 2022-02-15 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0022_auto_20220215_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='otp',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
