# Generated by Django 3.2.11 on 2022-02-23 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0024_sent_mails_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='group_creation',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='group_edition',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
