# Generated by Django 3.2.11 on 2022-03-04 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0025_auto_20220223_1230'),
    ]

    operations = [
        migrations.CreateModel(
            name='users_group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_id', models.EmailField(max_length=254, null=True)),
                ('group_name', models.CharField(max_length=150, null=True)),
            ],
        ),
    ]
