# Generated by Django 3.2.11 on 2022-04-02 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0026_users_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='on_creation_password',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
